"""
src/tests/test_alphalab_ci.py
-----------------------------
Baseline test suite for CI pipeline.
Covers: data validation, feature engineering, API health, model loading.

Run locally:
    pytest src/tests/ -v
"""

import pytest
import pandas as pd
import numpy as np
from pathlib import Path
from unittest.mock import patch, MagicMock

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parents[2]
FEATURES_PATH = ROOT / "data" / "features" / "all_factors.parquet"
BASELINE_PATH = ROOT / "data" / "features" / "baseline_stats.parquet"


# ═════════════════════════════════════════════════════════════════════════════
# 1. Data & Feature Tests
# ═════════════════════════════════════════════════════════════════════════════

class TestFeatureData:

    def test_all_factors_file_exists(self):
        """all_factors.parquet must exist after DVC repro."""
        assert FEATURES_PATH.exists(), \
            f"Missing: {FEATURES_PATH}. Run `dvc repro` to generate features."

    def test_all_factors_not_empty(self):
        """Feature file must have rows."""
        if not FEATURES_PATH.exists():
            pytest.skip("all_factors.parquet not present — skipping")
        df = pd.read_parquet(FEATURES_PATH)
        assert len(df) > 0, "all_factors.parquet is empty"

    def test_all_factors_has_numeric_columns(self):
        """Must have at least 10 numeric factor columns."""
        if not FEATURES_PATH.exists():
            pytest.skip("all_factors.parquet not present — skipping")
        df = pd.read_parquet(FEATURES_PATH)
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        assert len(numeric_cols) >= 10, \
            f"Expected ≥10 numeric columns, got {len(numeric_cols)}: {numeric_cols}"

    def test_no_all_null_columns(self):
        """No factor column should be 100% null."""
        if not FEATURES_PATH.exists():
            pytest.skip("all_factors.parquet not present — skipping")
        df = pd.read_parquet(FEATURES_PATH)
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            null_rate = df[col].isna().mean()
            assert null_rate < 1.0, f"Column '{col}' is entirely null"

    def test_baseline_stats_file_exists(self):
        """baseline_stats.parquet must exist (generated by calculate_baseline.py)."""
        assert BASELINE_PATH.exists(), \
            f"Missing: {BASELINE_PATH}. Run `python src/monitoring/calculate_baseline.py`"

    def test_baseline_stats_has_required_columns(self):
        """Baseline must contain mean, std, p50, null_rate columns."""
        if not BASELINE_PATH.exists():
            pytest.skip("baseline_stats.parquet not present — skipping")
        df = pd.read_parquet(BASELINE_PATH)
        required = {"mean", "std", "p50", "null_rate", "p25", "p75"}
        missing = required - set(df.columns)
        assert not missing, f"Baseline stats missing columns: {missing}"

    def test_baseline_stats_not_empty(self):
        """Baseline must have at least 10 features."""
        if not BASELINE_PATH.exists():
            pytest.skip("baseline_stats.parquet not present — skipping")
        df = pd.read_parquet(BASELINE_PATH)
        assert len(df) >= 10, f"Expected ≥10 features in baseline, got {len(df)}"


# ═════════════════════════════════════════════════════════════════════════════
# 2. Data Validation Tests
# ═════════════════════════════════════════════════════════════════════════════

class TestDataValidation:

    def test_factor_values_are_finite(self):
        """Factor columns must not contain inf or -inf."""
        if not FEATURES_PATH.exists():
            pytest.skip("all_factors.parquet not present — skipping")
        df = pd.read_parquet(FEATURES_PATH)
        numeric = df.select_dtypes(include=[np.number])
        inf_cols = [c for c in numeric.columns if np.isinf(numeric[c]).any()]
        assert not inf_cols, f"Infinite values found in columns: {inf_cols}"

    def test_factor_null_rate_acceptable(self):
        """No factor column should have >50% nulls."""
        if not FEATURES_PATH.exists():
            pytest.skip("all_factors.parquet not present — skipping")
        df = pd.read_parquet(FEATURES_PATH)
        numeric = df.select_dtypes(include=[np.number])
        bad_cols = [(c, df[c].isna().mean()) for c in numeric.columns
                    if df[c].isna().mean() > 0.5]
        assert not bad_cols, \
            f"Columns with >50% nulls: {[(c, f'{r:.0%}') for c, r in bad_cols]}"

    def test_date_column_present(self):
        """Feature file must have a date column."""
        if not FEATURES_PATH.exists():
            pytest.skip("all_factors.parquet not present — skipping")
        df = pd.read_parquet(FEATURES_PATH)
        date_candidates = [c for c in df.columns if "date" in c.lower()]
        has_datetime_index = isinstance(df.index, pd.DatetimeIndex)
        assert date_candidates or has_datetime_index, \
            "No date column or DatetimeIndex found in all_factors.parquet"


# ═════════════════════════════════════════════════════════════════════════════
# 3. API Tests (mocked — no running container needed in CI)
# ═════════════════════════════════════════════════════════════════════════════

class TestAPIStructure:

    def test_fastapi_app_importable(self):
        """FastAPI app module must be importable without errors."""
        try:
            import importlib
            # Try common app entry point names — adjust to match yours
            for module_name in ["api.main", "app.main", "main"]:
                spec = importlib.util.find_spec(module_name)
                if spec is not None:
                    return  # found it
            pytest.skip("Could not locate FastAPI app module — skipping import test")
        except Exception as e:
            pytest.fail(f"FastAPI app import failed: {e}")

    def test_health_endpoint_logic(self):
        """Health check should return status ok."""
        # Test the logic directly without spinning up the server
        health_response = {"status": "ok"}
        assert health_response["status"] == "ok"

    def test_predict_input_schema(self):
        """Prediction input must accept a list of ticker symbols."""
        sample_input = {"tickers": ["RELIANCE", "TCS", "INFY"], "top_n": 10}
        assert isinstance(sample_input["tickers"], list)
        assert len(sample_input["tickers"]) > 0
        assert isinstance(sample_input["top_n"], int)


# ═════════════════════════════════════════════════════════════════════════════
# 4. Monitoring Tests
# ═════════════════════════════════════════════════════════════════════════════

class TestMonitoring:

    def test_calculate_baseline_importable(self):
        """calculate_baseline module must import cleanly."""
        try:
            from monitoring.calculate_baseline import calculate_baseline, compute_baseline_stats
        except ImportError as e:
            pytest.fail(f"Cannot import calculate_baseline: {e}")

    def test_compute_baseline_stats_correctness(self):
        """compute_baseline_stats must produce correct mean and std."""
        from monitoring.calculate_baseline import compute_baseline_stats

        # Synthetic data with known stats
        df = pd.DataFrame({
            "date": pd.date_range("2024-01-01", periods=100),
            "momentum_rank": np.random.randn(100) * 10 + 50,
            "value_rank":    np.random.randn(100) * 5  + 30,
        })

        stats = compute_baseline_stats(df, ["momentum_rank", "value_rank"])

        assert "momentum_rank" in stats.index
        assert "value_rank" in stats.index
        assert "mean" in stats.columns
        assert "std" in stats.columns
        assert "p50" in stats.columns
        assert "null_rate" in stats.columns

        # Mean should be close to 50 for momentum_rank
        assert abs(stats.loc["momentum_rank", "mean"] - 50) < 5, \
            "Baseline mean deviates too much from expected value"

    def test_baseline_null_rate_zero_for_clean_data(self):
        """null_rate must be 0.0 for a column with no nulls."""
        from monitoring.calculate_baseline import compute_baseline_stats

        df = pd.DataFrame({
            "date":        pd.date_range("2024-01-01", periods=50),
            "clean_factor": np.ones(50),
        })
        stats = compute_baseline_stats(df, ["clean_factor"])
        assert stats.loc["clean_factor", "null_rate"] == 0.0

    def test_baseline_null_rate_nonzero_for_dirty_data(self):
        """null_rate must reflect actual missing fraction."""
        from monitoring.calculate_baseline import compute_baseline_stats

        arr = np.ones(100, dtype=float)
        arr[:20] = np.nan   # 20% nulls
        df = pd.DataFrame({
            "date":         pd.date_range("2024-01-01", periods=100),
            "dirty_factor": arr,
        })
        stats = compute_baseline_stats(df, ["dirty_factor"])
        assert abs(stats.loc["dirty_factor", "null_rate"] - 0.2) < 0.01


# ═════════════════════════════════════════════════════════════════════════════
# 5. Smoke Tests
# ═════════════════════════════════════════════════════════════════════════════

class TestSmoke:

    def test_python_version(self):
        """Python must be 3.9 or higher."""
        import sys
        assert sys.version_info >= (3, 9), \
            f"Python 3.9+ required, got {sys.version}"

    def test_required_packages_importable(self):
        """All core packages must be importable."""
        packages = [
            "pandas", "numpy", "xgboost", "sklearn",
            "fastapi", "mlflow", "dvc", "yfinance",
        ]
        failed = []
        for pkg in packages:
            try:
                __import__(pkg)
            except ImportError:
                failed.append(pkg)
        assert not failed, f"Required packages not importable: {failed}"

    def test_dvc_config_exists(self):
        """DVC must be initialised (dvc.yaml or .dvc/ must exist)."""
        dvc_dir = ROOT / ".dvc"
        dvc_yaml = ROOT / "dvc.yaml"
        assert dvc_dir.exists() or dvc_yaml.exists(), \
            "DVC not initialised — missing .dvc/ and dvc.yaml"